/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_usuario;

import java.awt.Container;
import javax.ws.rs.ClientErrorException;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.WebTarget;
import java.lang.Exception;
import com.rabbitmq.client.*;
import java.lang.Exception;
import com.rabbitmq.client.*;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.TimeoutException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pfsel
 */
public class JFPrincipal extends javax.swing.JFrame {

    public Container painelPrincipal;
    private ClienteRobot c;
    private ArrayList<String> posicoes;
    private FilaDeMensagens fila;
    private static final String EXCHANGE_NAME = "logs";
    private DefaultTableModel modelo;

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() throws Exception {
         JOptionPane.showMessageDialog(this, "Sem informação de modo de jogo",
                    "Opa!",
                    JOptionPane.WARNING_MESSAGE);
        initComponents();
        this.painelPrincipal = this.getContentPane();
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema supervisório");
        this.travaBotoes();
        this.c = new ClienteRobot();
        this.fila = new FilaDeMensagens("guest","guest",this);
        posicoes = new ArrayList<String>();
        modelo = (DefaultTableModel) JTTabelaPos.getModel();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGMODO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JBBack = new javax.swing.JButton();
        JBForward = new javax.swing.JButton();
        JBRight = new javax.swing.JButton();
        JBLeft = new javax.swing.JButton();
        JRBManual = new javax.swing.JRadioButton();
        JRBAutonomo = new javax.swing.JRadioButton();
        JTFPrincipal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTTabelaPos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/baixo.png"))); // NOI18N
        JBBack.setEnabled(false);
        JBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBackActionPerformed(evt);
            }
        });
        jPanel1.add(JBBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        JBForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cima.png"))); // NOI18N
        JBForward.setEnabled(false);
        JBForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBForwardActionPerformed(evt);
            }
        });
        jPanel1.add(JBForward, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        JBRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/direita.png"))); // NOI18N
        JBRight.setEnabled(false);
        JBRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRightActionPerformed(evt);
            }
        });
        jPanel1.add(JBRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        JBLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/esquerda.png"))); // NOI18N
        JBLeft.setEnabled(false);
        JBLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLeftActionPerformed(evt);
            }
        });
        jPanel1.add(JBLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        JBGMODO.add(JRBManual);
        JRBManual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JRBManual.setText("MANUAL");
        JRBManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBManualActionPerformed(evt);
            }
        });
        jPanel1.add(JRBManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        JBGMODO.add(JRBAutonomo);
        JRBAutonomo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JRBAutonomo.setText("AUTÔNOMO");
        jPanel1.add(JRBAutonomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(JTFPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 180, -1));

        JTTabelaPos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caça n°", "Posição (x,y)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTTabelaPos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBManualActionPerformed
        this.liberaBotoes();
    }//GEN-LAST:event_JRBManualActionPerformed

    private void JBRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRightActionPerformed
        GerenciaThread g = new GerenciaThread("/direita");
        g.start();
        JTFPrincipal.setText("direita");
    }//GEN-LAST:event_JBRightActionPerformed


    private void JBLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLeftActionPerformed
        GerenciaThread g = new GerenciaThread("/esquerda");
        g.start();
        JTFPrincipal.setText("esquerda");
    }//GEN-LAST:event_JBLeftActionPerformed

    private void JBForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBForwardActionPerformed
        GerenciaThread g = new GerenciaThread("/frente");
        g.start();
        JTFPrincipal.setText("frente");
    }//GEN-LAST:event_JBForwardActionPerformed

    private void JBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBackActionPerformed
        GerenciaThread g = new GerenciaThread("/re");
        g.start();
        JTFPrincipal.setText("re");
    }//GEN-LAST:event_JBBackActionPerformed


    public void travaBotoes() {
        JBBack.setEnabled(false);
        JBForward.setEnabled(false);
        JBLeft.setEnabled(false);
        JBRight.setEnabled(false);
        JRBAutonomo.setEnabled(false);
        JRBManual.setEnabled(false);
        JTFPrincipal.setEnabled(false);
     

    }

    public void liberaBotoes() {
        JBBack.setEnabled(true);
        JBForward.setEnabled(true);
        JBLeft.setEnabled(true);
        JBRight.setEnabled(true);
        JRBAutonomo.setEnabled(true);
        JRBManual.setEnabled(true);
        JTFPrincipal.setEnabled(true);
        
    }
    
    public void iniciaTabela(){
        this.criaTabela();
    }
    
    private void criaTabela(){
        
        //this.removeTabela();
      
        String[] linha = new String[2];
       
        if(modelo.getRowCount() != 0) {
          for (int i = 0; i < posicoes.size() ; i++){
            modelo.removeRow(0);
        }
        }
        for(int i = 0; i < posicoes.size(); i++){
            
            linha[0] = Integer.toString(i+1);
            linha[1] = posicoes.get(i);
            System.out.println(linha[1]);
            modelo.addRow(linha);
            
        
        
        
        }
   }
     
    public void recebePosicoes(ArrayList<String> posicoes){        
        this.posicoes=posicoes;
    }
    public void modoManual(){
        this.travaBotoes();
        JBBack.setEnabled(true);
        JBForward.setEnabled(true);
        JBLeft.setEnabled(true);
        JBRight.setEnabled(true);
        JRBManual.setEnabled(true);
        JRBManual.setSelected(true);
        JTFPrincipal.setEnabled(true);        
   }
    
    public void modoAutomatico(){
        this.travaBotoes();
        JRBAutonomo.setSelected(true);
        JRBAutonomo.setEnabled(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFPrincipal().setVisible(true);
                } catch (Exception e) {
                    System.out.println("erro frente");
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBack;
    private javax.swing.JButton JBForward;
    private javax.swing.ButtonGroup JBGMODO;
    private javax.swing.JButton JBLeft;
    private javax.swing.JButton JBRight;
    private javax.swing.JRadioButton JRBAutonomo;
    private javax.swing.JRadioButton JRBManual;
    private javax.swing.JTextField JTFPrincipal;
    private javax.swing.JTable JTTabelaPos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
